name: qlora-dialogues
# Tested with:
#   conda env create --prefix ./env -f environment.yml
#
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - rust=1.64.0
  - pip
  - pip:
    - bitsandbytes==0.39.0
    - transformers @ git+https://github.com/huggingface/transformers.git@8f093fb799246f7dd9104ff44728da0c53a9f67a
    - peft @ git+https://github.com/huggingface/peft.git@189a6b8e357ecda05ccde13999e4c35759596a67
    - accelerate @ git+https://github.com/huggingface/accelerate.git@665d5180fcc01d5700f7a9aa3f9bdb75c6055dce
    - einops==0.6.1
    - evaluate==0.4.0
    - scikit-learn==1.2.2
    - sentencepiece==0.1.99
    - git+https://github.com/Tomiinek/MultiWOZ_Evaluation.git@1d03eb438daf30e1f0a5f958f5c78fa0c56eaa38
    # Reporting tool (highly recommended). Better TensorBoard.
    - wandb==0.15.3
    # Oplatek's debugging tools - completely optional.
    - ipdb
    - exp-notifier
